### ISSUE TITLE
Proxy autodetect / is not working

### ISSUE THREAD

**Issue by melimind** [MarkusBernhardt/proxy-vole#6] opened 2016-12-05 06:01 UTC
Hello,

Something is not right with the forked edition of proxy-vole when it comes to Proxy auto detection.

On my PC IE proxy setting is set to Autodetect. 

As you can see from the screen shot the original proxy-vole (right) detects the proxy script and correctly find a proxy host and port.
This is not a case for a forked edition (left).

![image](https://cloud.githubusercontent.com/assets/24381263/20875120/708f6490-bab8-11e6-926f-2ade423aa8c3.png)

Thanks

Mindaugas

**Comment by MarkusBernhardt** [comment] 2016-12-05 08:41
Hmm. That's weird. Seems it cannot find the WPAD location. Will fly through the code for ideas.

**Comment by MarkusBernhardt** [comment] 2016-12-05 08:42
BTW. I'm using auto detection every day.

**Comment by davidhedley** [comment] 2017-02-08 12:50
I am seeing a similar problem. When I use the "Automatically detect settings" option in windows Control Panel, it does not detect the proxy, although all other Windows apps are successfully using the proxy.

If I enter the URL of the wpad.dat in the "Use automatic configuration script" field of the Internet Properties, then proxy-vole *does* find the proxy.

Your code is:
```
Logger.log(getClass(), LogLevel.TRACE, "Autodetecting script URL.");
// This will take some time.
DWORD dwAutoDetectFlags = new DWORD(WinHttp.WINHTTP_AUTO_DETECT_TYPE_DHCP | WinHttp.WINHTTP_AUTO_DETECT_TYPE_DNS_A);
LPWSTR ppwszAutoConfigUrl = new LPWSTR();
boolean result = WinHttp.INSTANCE.WinHttpDetectAutoProxyConfigUrl(dwAutoDetectFlags, ppwszAutoConfigUrl);
```

in my case `result` is returning false, hence it doesn't get the PAC URL. We are using DNS for WPAD.

Any ideas?

**Comment by davidhedley** [comment] 2017-02-08 14:20
As a followup, I am currently doing the following which works for me:

```
proxySearch = ProxySearch.getDefaultProxySearch();

// Try the proxy-vole default search strategy
ProxySelector ps = proxySearch.getProxySelector();
// This returns null sometimes if automatic proxy detection is selected, so try WPAD ourselves as a last resort
if (ps == null) {
	try {
		ps = new WpadProxySearchStrategy().getProxySelector();
	} catch (ProxyException e) {
		log.error("Failed to get ProxySelector for WPAD");
	}
}
ProxySelector.setDefault(ps);
```

**Comment by NameetaJain** [comment] 2017-04-19 05:05
Hello,

I am facing same issue, autodetect flag is correctly detected, but library is not able to read the URL.
boolean result = WinHttp.INSTANCE.WinHttpDetectAutoProxyConfigUrl(dwAutoDetectFlags, ppwszAutoConfigUrl);
int error = Native.getLastError();

GetLastError is returning 87 (Invalid parameter)
Please support, as we want seamless proxy behavior as that of windows.
Please support.

**Comment by MarkusBernhardt** [comment] 2017-05-05 09:26
I will now start looking into this. Could you help me testing this, because I cannot replicate this behavior in out networks.

**Comment by NameetaJain** [comment] 2017-05-05 10:01
Sure. I have also raised a separate issue "Proxy autodetect not working #12" which has some more specific details. We can discuss on that thread.

**Comment by davidhedley** [comment] 2017-05-05 14:17
Yes sure. Let me know as and when you have builds to test

**Comment by phansson** [comment] 2017-08-06 21:53
I've created pull request #21 which fixes this problem. As pointed out by others the problem is that current code uses a `LPWSTR` as the second argument, but it should have been *a pointer* to a LPWSTR.

**Comment by MarkusBernhardt** [comment] 2017-09-29 12:57
Many, many thanks chanson for this fix. Will be released this weekend.
Closing this issue therefore.

**Closed by MarkusBernhardt** 2017-09-29 12:57 UTC
Labels: bug
