### ISSUE TITLE
Detecting IE proxy settings hangs for 4 minutes

### ISSUE THREAD

**Issue by jpalmiero** [MarkusBernhardt/proxy-vole#8] opened 2017-02-27 10:23 UTC
I am running into an issue where a java app will literally hang for 4 minutes on the line in bold below.  it will ultimate come back and not detect a proxy setting, but I would like for it fail fast.  Any thoughts on what might be causing this.

public IEProxyConfig readIEProxyConfig() {

		// Retrieve the IE proxy configuration.
		long start = System.currentTimeMillis();
		**WinHttpCurrentUserIEProxyConfig winHttpCurrentUserIeProxyConfig = new WinHttpCurrentUserIEProxyConfig();**
		long stop = System.currentTimeMillis();
		
		long difference = stop - start;
		System.out.println(difference);

**Comment by lwahonen** [comment] 2017-03-19 18:21
That line creates a Structure object, which wakes up JNA and probably makes JNA do the dispatch dll loading too.

I created a version of proxy-vole using Bernhardt's java sources but with a traditional JNI dll instead, the jar+dependencies are much lighter and the startup seems faster. The downside of course is, you need to compile the DLL yourself or trust someone else's binaries. Let me know if you want a copy of the jar for testing, not sure if it's of release quality yet.

**Comment by MarkusBernhardt** [comment] 2017-05-05 12:02
Yes, I can replicate that. At least somewhat. This line initializes JNA, when called the first time. On my machine this takes roughly 1 second for the first call. All follow up calls do not have the problem.

Could you please do this test again and execute the method twice.

**Comment by MarkusBernhardt** [comment] 2017-09-29 13:08
Cannot reproduce a minute long delay. Closing.

**Closed by MarkusBernhardt** 2017-09-29 13:08 UTC
